### ISSUE TITLE
Consider using \9

### ISSUE THREAD

**Issue by valtlai** [MadLittleMods/postcss-increase-specificity#11]
`:not(#\9)`, where `\9` is a tab character, can be used. It works in the same way as `:not(#\20)` but is one character shorter.

Other alternatives are `\A`, `\C` and `\D`.
* https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute
   (*The value must not contain any ASCII whitespace.*)
* https://infra.spec.whatwg.org/#ascii-whitespace
   (*An ASCII whitespace is U+0009 TAB, U+000A LF, U+000C FF, U+000D CR, or U+0020 SPACE.*)

**Comment by valtlai** [comment]
See PR #12

**Comment by iamstarkov** [comment]
What do we gain from having it one character shorter?

**Comment by iamstarkov** [comment]
> (An ASCII whitespace is U+0009 TAB, U+000A LF, U+000C FF, U+000D CR, or U+0020 SPACE.)

so its effectively what we have today

**Comment by MadLittleMods** [comment]
> I thought why not use a shorter one and save some bytes. But I understand this has no practical effect.
>
> @valtlai, https://github.com/MadLittleMods/postcss-increase-specificity/pull/12#issuecomment-304317070

Seems good to me 🤔
