### ISSUE TITLE
Use `:not(#\20)` stackable root to make selectors more specific

### ISSUE THREAD

**Issue by iamstarkov** [MadLittleMods/postcss-increase-specificity#8]
> use :not(#\20), :not(.\20) and :not(\20) instead of generating unlikely
 > appearing ids…  
>
 > — https://twitter.com/subzey/status/829050478721896448
>
 > Rationale: \20 is a css escape for U+0020 Space, and neither classname,
 > nor id, nor tagname can contain a space
>
 > — https://twitter.com/subzey/status/829051085885153280

I tried to solve the same issue as you in [jss](https://github.com/cssinjs/jss/) land, and the way to use `:not(#\20)` instead of `:root` seems to be more efficient in increasing selectors' specificity

Related:
* https://github.com/iamstarkov/jss-increase-specificity/blob/master/index.js
* https://github.com/iamstarkov/jss-increase-id-specificity/blob/master/index.js

/cc @subzey

**Comment by MadLittleMods** [comment]
@iamstarkov Seems reasonable. PR welcome 😀

**Comment by iamstarkov** [comment]
@MadLittleMods PR #9 🎉

**Comment by iamstarkov** [comment]
@MadLittleMods are you PR was welcomed? =)

**Comment by MadLittleMods** [comment]
Published in [`postcss-increase-specificity@0.4.0`](https://github.com/MadLittleMods/postcss-increase-specificity/blob/master/CHANGELOG.md#v040---2017-5-18), https://www.npmjs.com/package/postcss-increase-specificity :tada:

Thanks to [@subzey](https://github.com/subzey) for the [idea](https://twitter.com/subzey/status/829050478721896448) and [@iamstarkov](https://github.com/iamstarkov) for the contribution [#9](https://github.com/MadLittleMods/postcss-increase-specificity/pull/9) 💖
